# This file has been generated by node2nix 1.1.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "archiver-1.1.0" = {
      name = "archiver";
      packageName = "archiver";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/archiver/-/archiver-1.1.0.tgz";
        sha1 = "e1e8c4d356cf155308f351d60cc18cb6fb2344ee";
      };
    };
    "argparse-1.0.9" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.9.tgz";
        sha1 = "73d83bc263f86e97f8cc4f6bae1b0e90a7d22c86";
      };
    };
    "assert-1.4.1" = {
      name = "assert";
      packageName = "assert";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert/-/assert-1.4.1.tgz";
        sha1 = "99912d591836b5a6f5b345c0f07eefc08fc65d91";
      };
    };
    "prompt-1.0.0" = {
      name = "prompt";
      packageName = "prompt";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prompt/-/prompt-1.0.0.tgz";
        sha1 = "8e57123c396ab988897fb327fd3aedc3e735e4fe";
      };
    };
    "request-2.75.0" = {
      name = "request";
      packageName = "request";
      version = "2.75.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.75.0.tgz";
        sha1 = "d2b8268a286da13eaa5d01adf5d18cc90f657d93";
      };
    };
    "archiver-utils-1.3.0" = {
      name = "archiver-utils";
      packageName = "archiver-utils";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/archiver-utils/-/archiver-utils-1.3.0.tgz";
        sha1 = "e50b4c09c70bf3d680e32ff1b7994e9f9d895174";
      };
    };
    "async-2.0.1" = {
      name = "async";
      packageName = "async";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.0.1.tgz";
        sha1 = "b709cc0280a9c36f09f4536be823c838a9049e25";
      };
    };
    "buffer-crc32-0.2.5" = {
      name = "buffer-crc32";
      packageName = "buffer-crc32";
      version = "0.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.2.5.tgz";
        sha1 = "db003ac2671e62ebd6ece78ea2c2e1b405736e91";
      };
    };
    "glob-7.1.1" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.1.tgz";
        sha1 = "805211df04faaf1c63a3600306cdf5ade50b2ec8";
      };
    };
    "lodash-4.16.4" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.16.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.16.4.tgz";
        sha1 = "01ce306b9bad1319f2a5528674f88297aeb70127";
      };
    };
    "readable-stream-2.1.5" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.1.5.tgz";
        sha1 = "66fa8b720e1438b364681f2ad1a63c618448c9d0";
      };
    };
    "tar-stream-1.5.2" = {
      name = "tar-stream";
      packageName = "tar-stream";
      version = "1.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/tar-stream/-/tar-stream-1.5.2.tgz";
        sha1 = "fbc6c6e83c1a19d4cb48c7d96171fc248effc7bf";
      };
    };
    "zip-stream-1.1.0" = {
      name = "zip-stream";
      packageName = "zip-stream";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/zip-stream/-/zip-stream-1.1.0.tgz";
        sha1 = "2ad479fffc168e05a888e8c348ff6813b3f13733";
      };
    };
    "graceful-fs-4.1.9" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.9.tgz";
        sha1 = "baacba37d19d11f9d146d3578bc99958c3787e29";
      };
    };
    "lazystream-1.0.0" = {
      name = "lazystream";
      packageName = "lazystream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lazystream/-/lazystream-1.0.0.tgz";
        sha1 = "f6995fe0f820392f61396be89462407bb77168e4";
      };
    };
    "normalize-path-2.0.1" = {
      name = "normalize-path";
      packageName = "normalize-path";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-path/-/normalize-path-2.0.1.tgz";
        sha1 = "47886ac1662760d4261b7d979d241709d3ce3f7a";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "inflight-1.0.5" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.5.tgz";
        sha1 = "db3204cd5a9de2e6cd890b85c6e2f66bcf4f620a";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "minimatch-3.0.3" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.3.tgz";
        sha1 = "2a4e4090b96b2db06a9d7df01055a62a77c9b774";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "brace-expansion-1.1.6" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.6.tgz";
        sha1 = "7197d7eaa9b87e648390ea61fc66c84427420df9";
      };
    };
    "balanced-match-0.4.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-0.4.2.tgz";
        sha1 = "cb3f3e3c732dc0f01ee70b403f302e61d7709838";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "buffer-shims-1.0.0" = {
      name = "buffer-shims";
      packageName = "buffer-shims";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-shims/-/buffer-shims-1.0.0.tgz";
        sha1 = "9978ce317388c649ad8793028c3477ef044a8b51";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "process-nextick-args-1.0.7" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-1.0.7.tgz";
        sha1 = "150e20b756590ad3f91093f25a4f2ad8bff30ba3";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "bl-1.1.2" = {
      name = "bl";
      packageName = "bl";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bl/-/bl-1.1.2.tgz";
        sha1 = "fdca871a99713aa00d19e3bbba41c44787a65398";
      };
    };
    "end-of-stream-1.1.0" = {
      name = "end-of-stream";
      packageName = "end-of-stream";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.1.0.tgz";
        sha1 = "e9353258baa9108965efc41cb0ef8ade2f3cfb07";
      };
    };
    "xtend-4.0.1" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.1.tgz";
        sha1 = "a5c6d532be656e23db820efb943a1f04998d63af";
      };
    };
    "readable-stream-2.0.6" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.0.6.tgz";
        sha1 = "8f90341e68a53ccc928788dacfcd11b36eb9b78e";
      };
    };
    "once-1.3.3" = {
      name = "once";
      packageName = "once";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.3.3.tgz";
        sha1 = "b2e261557ce4c314ec8304f3fa82663e4297ca20";
      };
    };
    "compress-commons-1.1.0" = {
      name = "compress-commons";
      packageName = "compress-commons";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/compress-commons/-/compress-commons-1.1.0.tgz";
        sha1 = "9f4460bb1288564c7473916e0298aa3c320dcadb";
      };
    };
    "crc32-stream-1.0.0" = {
      name = "crc32-stream";
      packageName = "crc32-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/crc32-stream/-/crc32-stream-1.0.0.tgz";
        sha1 = "ea155e5e1d738ed3778438ffe92ffe2a141aeb3f";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "util-0.10.3" = {
      name = "util";
      packageName = "util";
      version = "0.10.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/util/-/util-0.10.3.tgz";
        sha1 = "7afb1afe50805246489e3db7fe0ed379336ac0f9";
      };
    };
    "inherits-2.0.1" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz";
        sha1 = "b17d08d326b4423e568eff719f91b0b1cbdf69f1";
      };
    };
    "colors-1.1.2" = {
      name = "colors";
      packageName = "colors";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.1.2.tgz";
        sha1 = "168a4701756b6a7f51a12ce0c97bfa28c084ed63";
      };
    };
    "pkginfo-0.4.0" = {
      name = "pkginfo";
      packageName = "pkginfo";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pkginfo/-/pkginfo-0.4.0.tgz";
        sha1 = "349dbb7ffd38081fcadc0853df687f0c7744cd65";
      };
    };
    "read-1.0.7" = {
      name = "read";
      packageName = "read";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/read/-/read-1.0.7.tgz";
        sha1 = "b3da19bd052431a97671d44a42634adf710b40c4";
      };
    };
    "revalidator-0.1.8" = {
      name = "revalidator";
      packageName = "revalidator";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/revalidator/-/revalidator-0.1.8.tgz";
        sha1 = "fece61bfa0c1b52a206bd6b18198184bdd523a3b";
      };
    };
    "utile-0.3.0" = {
      name = "utile";
      packageName = "utile";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/utile/-/utile-0.3.0.tgz";
        sha1 = "1352c340eb820e4d8ddba039a4fbfaa32ed4ef3a";
      };
    };
    "winston-2.1.1" = {
      name = "winston";
      packageName = "winston";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/winston/-/winston-2.1.1.tgz";
        sha1 = "3c9349d196207fd1bdff9d4bc43ef72510e3a12e";
      };
    };
    "mute-stream-0.0.6" = {
      name = "mute-stream";
      packageName = "mute-stream";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/mute-stream/-/mute-stream-0.0.6.tgz";
        sha1 = "48962b19e169fd1dfc240b3f1e7317627bbc47db";
      };
    };
    "async-0.9.2" = {
      name = "async";
      packageName = "async";
      version = "0.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-0.9.2.tgz";
        sha1 = "aea74d5e61c1f899613bf64bda66d4c78f2fd17d";
      };
    };
    "deep-equal-0.2.2" = {
      name = "deep-equal";
      packageName = "deep-equal";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-equal/-/deep-equal-0.2.2.tgz";
        sha1 = "84b745896f34c684e98f2ce0e42abaf43bba017d";
      };
    };
    "i-0.3.5" = {
      name = "i";
      packageName = "i";
      version = "0.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/i/-/i-0.3.5.tgz";
        sha1 = "1d2b854158ec8169113c6cb7f6b6801e99e211d5";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "ncp-1.0.1" = {
      name = "ncp";
      packageName = "ncp";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ncp/-/ncp-1.0.1.tgz";
        sha1 = "d15367e5cb87432ba117d2bf80fdf45aecfb4246";
      };
    };
    "rimraf-2.5.4" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.5.4.tgz";
        sha1 = "96800093cbf1a0c86bd95b4625467535c29dfa04";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "async-1.0.0" = {
      name = "async";
      packageName = "async";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-1.0.0.tgz";
        sha1 = "f8fc04ca3a13784ade9e1641af98578cfbd647a9";
      };
    };
    "colors-1.0.3" = {
      name = "colors";
      packageName = "colors";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.0.3.tgz";
        sha1 = "0433f44d809680fdeb60ed260f1b0c262e82a40b";
      };
    };
    "cycle-1.0.3" = {
      name = "cycle";
      packageName = "cycle";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cycle/-/cycle-1.0.3.tgz";
        sha1 = "21e80b2be8580f98b468f379430662b046c34ad2";
      };
    };
    "eyes-0.1.8" = {
      name = "eyes";
      packageName = "eyes";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/eyes/-/eyes-0.1.8.tgz";
        sha1 = "62cf120234c683785d902348a800ef3e0cc20bc0";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "pkginfo-0.3.1" = {
      name = "pkginfo";
      packageName = "pkginfo";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pkginfo/-/pkginfo-0.3.1.tgz";
        sha1 = "5b29f6a81f70717142e09e765bbeab97b4f81e21";
      };
    };
    "stack-trace-0.0.9" = {
      name = "stack-trace";
      packageName = "stack-trace";
      version = "0.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/stack-trace/-/stack-trace-0.0.9.tgz";
        sha1 = "a8f6eaeca90674c333e7c43953f275b451510695";
      };
    };
    "aws-sign2-0.6.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.6.0.tgz";
        sha1 = "14342dd38dbcc94d0e5b87d763cd63612c0e794f";
      };
    };
    "aws4-1.5.0" = {
      name = "aws4";
      packageName = "aws4";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws4/-/aws4-1.5.0.tgz";
        sha1 = "0a29ffb79c31c9e712eeb087e8e7a64b4a56d755";
      };
    };
    "caseless-0.11.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.11.0.tgz";
        sha1 = "715b96ea9841593cc33067923f5ec60ebda4f7d7";
      };
    };
    "combined-stream-1.0.5" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.5.tgz";
        sha1 = "938370a57b4a51dea2c77c15d5c5fdf895164009";
      };
    };
    "extend-3.0.0" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.0.tgz";
        sha1 = "5a474353b9f3353ddd8176dfd37b91c83a46f1d4";
      };
    };
    "forever-agent-0.6.1" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz";
        sha1 = "fbc71f0c41adeb37f96c577ad1ed42d8fdacca91";
      };
    };
    "form-data-2.0.0" = {
      name = "form-data";
      packageName = "form-data";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-2.0.0.tgz";
        sha1 = "6f0aebadcc5da16c13e1ecc11137d85f9b883b25";
      };
    };
    "har-validator-2.0.6" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-2.0.6.tgz";
        sha1 = "cdcbc08188265ad119b6a5a7c8ab70eecfb5d27d";
      };
    };
    "hawk-3.1.3" = {
      name = "hawk";
      packageName = "hawk";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hawk/-/hawk-3.1.3.tgz";
        sha1 = "078444bd7c1640b0fe540d2c9b73d59678e8e1c4";
      };
    };
    "http-signature-1.1.1" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.1.1.tgz";
        sha1 = "df72e267066cd0ac67fb76adf8e134a8fbcf91bf";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "mime-types-2.1.12" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.12.tgz";
        sha1 = "152ba256777020dd4663f54c2e7bc26381e71729";
      };
    };
    "node-uuid-1.4.7" = {
      name = "node-uuid";
      packageName = "node-uuid";
      version = "1.4.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.7.tgz";
        sha1 = "6da5a17668c4b3dd59623bda11cf7fa4c1f60a6f";
      };
    };
    "oauth-sign-0.8.2" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.8.2.tgz";
        sha1 = "46a6ab7f0aead8deae9ec0565780b7d4efeb9d43";
      };
    };
    "qs-6.2.1" = {
      name = "qs";
      packageName = "qs";
      version = "6.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.2.1.tgz";
        sha1 = "ce03c5ff0935bc1d9d69a9f14cbd18e568d67625";
      };
    };
    "stringstream-0.0.5" = {
      name = "stringstream";
      packageName = "stringstream";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/stringstream/-/stringstream-0.0.5.tgz";
        sha1 = "4e484cd4de5a0bbbee18e46307710a8a81621878";
      };
    };
    "tough-cookie-2.3.1" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.3.1.tgz";
        sha1 = "99c77dfbb7d804249e8a299d4cb0fd81fef083fd";
      };
    };
    "tunnel-agent-0.4.3" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.4.3.tgz";
        sha1 = "6373db76909fe570e08d73583365ed828a74eeeb";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "commander-2.9.0" = {
      name = "commander";
      packageName = "commander";
      version = "2.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.9.0.tgz";
        sha1 = "9c99094176e12240cb22d6c5146098400fe0f7d4";
      };
    };
    "is-my-json-valid-2.15.0" = {
      name = "is-my-json-valid";
      packageName = "is-my-json-valid";
      version = "2.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-my-json-valid/-/is-my-json-valid-2.15.0.tgz";
        sha1 = "936edda3ca3c211fd98f3b2d3e08da43f7b2915b";
      };
    };
    "pinkie-promise-2.0.1" = {
      name = "pinkie-promise";
      packageName = "pinkie-promise";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.1.tgz";
        sha1 = "2135d6dfa7a358c069ac9b178776288228450ffa";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "ansi-regex-2.0.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.0.0.tgz";
        sha1 = "c5061b6e0ef8a81775e50f5d66151bf6bf371107";
      };
    };
    "graceful-readlink-1.0.1" = {
      name = "graceful-readlink";
      packageName = "graceful-readlink";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-readlink/-/graceful-readlink-1.0.1.tgz";
        sha1 = "4cafad76bc62f02fa039b2f94e9a3dd3a391a725";
      };
    };
    "generate-function-2.0.0" = {
      name = "generate-function";
      packageName = "generate-function";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/generate-function/-/generate-function-2.0.0.tgz";
        sha1 = "6858fe7c0969b7d4e9093337647ac79f60dfbe74";
      };
    };
    "generate-object-property-1.2.0" = {
      name = "generate-object-property";
      packageName = "generate-object-property";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/generate-object-property/-/generate-object-property-1.2.0.tgz";
        sha1 = "9c0e1c40308ce804f4783618b937fa88f99d50d0";
      };
    };
    "jsonpointer-4.0.0" = {
      name = "jsonpointer";
      packageName = "jsonpointer";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonpointer/-/jsonpointer-4.0.0.tgz";
        sha1 = "6661e161d2fc445f19f98430231343722e1fcbd5";
      };
    };
    "is-property-1.0.2" = {
      name = "is-property";
      packageName = "is-property";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-property/-/is-property-1.0.2.tgz";
        sha1 = "57fe1c4e48474edd65b09911f26b1cd4095dda84";
      };
    };
    "pinkie-2.0.4" = {
      name = "pinkie";
      packageName = "pinkie";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie/-/pinkie-2.0.4.tgz";
        sha1 = "72556b80cfa0d48a974e80e77248e80ed4f7f870";
      };
    };
    "hoek-2.16.3" = {
      name = "hoek";
      packageName = "hoek";
      version = "2.16.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoek/-/hoek-2.16.3.tgz";
        sha1 = "20bb7403d3cea398e91dc4710a8ff1b8274a25ed";
      };
    };
    "boom-2.10.1" = {
      name = "boom";
      packageName = "boom";
      version = "2.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/boom/-/boom-2.10.1.tgz";
        sha1 = "39c8918ceff5799f83f9492a848f625add0c766f";
      };
    };
    "cryptiles-2.0.5" = {
      name = "cryptiles";
      packageName = "cryptiles";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cryptiles/-/cryptiles-2.0.5.tgz";
        sha1 = "3bdfecdc608147c1c67202fa291e7dca59eaa3b8";
      };
    };
    "sntp-1.0.9" = {
      name = "sntp";
      packageName = "sntp";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/sntp/-/sntp-1.0.9.tgz";
        sha1 = "6541184cc90aeea6c6e7b35e2659082443c66198";
      };
    };
    "assert-plus-0.2.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-0.2.0.tgz";
        sha1 = "d74e1b87e7affc0db8aadb7021f3fe48101ab234";
      };
    };
    "jsprim-1.3.1" = {
      name = "jsprim";
      packageName = "jsprim";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsprim/-/jsprim-1.3.1.tgz";
        sha1 = "2a7256f70412a29ee3670aaca625994c4dcff252";
      };
    };
    "sshpk-1.10.1" = {
      name = "sshpk";
      packageName = "sshpk";
      version = "1.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sshpk/-/sshpk-1.10.1.tgz";
        sha1 = "30e1a5d329244974a1af61511339d595af6638b0";
      };
    };
    "extsprintf-1.0.2" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.0.2.tgz";
        sha1 = "e1080e0658e300b06294990cc70e1502235fd550";
      };
    };
    "json-schema-0.2.3" = {
      name = "json-schema";
      packageName = "json-schema";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema/-/json-schema-0.2.3.tgz";
        sha1 = "b480c892e59a2f05954ce727bd3f2a4e882f9e13";
      };
    };
    "verror-1.3.6" = {
      name = "verror";
      packageName = "verror";
      version = "1.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.3.6.tgz";
        sha1 = "cff5df12946d297d2baaefaa2689e25be01c005c";
      };
    };
    "asn1-0.2.3" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz";
        sha1 = "dac8787713c9966849fc8180777ebe9c1ddf3b86";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "dashdash-1.14.0" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.0.tgz";
        sha1 = "29e486c5418bf0f356034a993d51686a33e84141";
      };
    };
    "getpass-0.1.6" = {
      name = "getpass";
      packageName = "getpass";
      version = "0.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/getpass/-/getpass-0.1.6.tgz";
        sha1 = "283ffd9fc1256840875311c1b60e8c40187110e6";
      };
    };
    "jsbn-0.1.0" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-0.1.0.tgz";
        sha1 = "650987da0dd74f4ebf5a11377a2aa2d273e97dfd";
      };
    };
    "tweetnacl-0.14.3" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.3.tgz";
        sha1 = "3da382f670f25ded78d7b3d1792119bca0b7132d";
      };
    };
    "jodid25519-1.0.2" = {
      name = "jodid25519";
      packageName = "jodid25519";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jodid25519/-/jodid25519-1.0.2.tgz";
        sha1 = "06d4912255093419477d425633606e0e90782967";
      };
    };
    "ecc-jsbn-0.1.1" = {
      name = "ecc-jsbn";
      packageName = "ecc-jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.1.tgz";
        sha1 = "0fc73a9ed5f0d53c38193398523ef7e543777505";
      };
    };
    "bcrypt-pbkdf-1.0.0" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.0.tgz";
        sha1 = "3ca76b85241c7170bf7d9703e7b9aa74630040d4";
      };
    };
    "mime-db-1.24.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.24.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.24.0.tgz";
        sha1 = "e2d13f939f0016c6e4e9ad25a8652f126c467f0c";
      };
    };
  };
  args = {
    name = "plonetheme-upload";
    packageName = "plonetheme-upload";
    version = (builtins.fromJSON (builtins.readFile ./package.json)).version;
    src = ./.;
    dependencies = [
      (sources."archiver-1.1.0" // {
        dependencies = [
          (sources."archiver-utils-1.3.0" // {
            dependencies = [
              sources."graceful-fs-4.1.9"
              sources."lazystream-1.0.0"
              sources."normalize-path-2.0.1"
            ];
          })
          sources."async-2.0.1"
          sources."buffer-crc32-0.2.5"
          (sources."glob-7.1.1" // {
            dependencies = [
              sources."fs.realpath-1.0.0"
              (sources."inflight-1.0.5" // {
                dependencies = [
                  sources."wrappy-1.0.2"
                ];
              })
              sources."inherits-2.0.3"
              (sources."minimatch-3.0.3" // {
                dependencies = [
                  (sources."brace-expansion-1.1.6" // {
                    dependencies = [
                      sources."balanced-match-0.4.2"
                      sources."concat-map-0.0.1"
                    ];
                  })
                ];
              })
              (sources."once-1.4.0" // {
                dependencies = [
                  sources."wrappy-1.0.2"
                ];
              })
              sources."path-is-absolute-1.0.1"
            ];
          })
          sources."lodash-4.16.4"
          (sources."readable-stream-2.1.5" // {
            dependencies = [
              sources."buffer-shims-1.0.0"
              sources."core-util-is-1.0.2"
              sources."inherits-2.0.3"
              sources."isarray-1.0.0"
              sources."process-nextick-args-1.0.7"
              sources."string_decoder-0.10.31"
              sources."util-deprecate-1.0.2"
            ];
          })
          (sources."tar-stream-1.5.2" // {
            dependencies = [
              (sources."bl-1.1.2" // {
                dependencies = [
                  (sources."readable-stream-2.0.6" // {
                    dependencies = [
                      sources."core-util-is-1.0.2"
                      sources."inherits-2.0.3"
                      sources."isarray-1.0.0"
                      sources."process-nextick-args-1.0.7"
                      sources."string_decoder-0.10.31"
                      sources."util-deprecate-1.0.2"
                    ];
                  })
                ];
              })
              (sources."end-of-stream-1.1.0" // {
                dependencies = [
                  (sources."once-1.3.3" // {
                    dependencies = [
                      sources."wrappy-1.0.2"
                    ];
                  })
                ];
              })
              sources."xtend-4.0.1"
            ];
          })
          (sources."zip-stream-1.1.0" // {
            dependencies = [
              (sources."compress-commons-1.1.0" // {
                dependencies = [
                  sources."crc32-stream-1.0.0"
                  sources."normalize-path-2.0.1"
                ];
              })
            ];
          })
        ];
      })
      (sources."argparse-1.0.9" // {
        dependencies = [
          sources."sprintf-js-1.0.3"
        ];
      })
      (sources."assert-1.4.1" // {
        dependencies = [
          (sources."util-0.10.3" // {
            dependencies = [
              sources."inherits-2.0.1"
            ];
          })
        ];
      })
      (sources."prompt-1.0.0" // {
        dependencies = [
          sources."colors-1.1.2"
          sources."pkginfo-0.4.0"
          (sources."read-1.0.7" // {
            dependencies = [
              sources."mute-stream-0.0.6"
            ];
          })
          sources."revalidator-0.1.8"
          (sources."utile-0.3.0" // {
            dependencies = [
              sources."async-0.9.2"
              sources."deep-equal-0.2.2"
              sources."i-0.3.5"
              (sources."mkdirp-0.5.1" // {
                dependencies = [
                  sources."minimist-0.0.8"
                ];
              })
              sources."ncp-1.0.1"
              (sources."rimraf-2.5.4" // {
                dependencies = [
                  (sources."glob-7.1.1" // {
                    dependencies = [
                      sources."fs.realpath-1.0.0"
                      (sources."inflight-1.0.5" // {
                        dependencies = [
                          sources."wrappy-1.0.2"
                        ];
                      })
                      sources."inherits-2.0.3"
                      (sources."minimatch-3.0.3" // {
                        dependencies = [
                          (sources."brace-expansion-1.1.6" // {
                            dependencies = [
                              sources."balanced-match-0.4.2"
                              sources."concat-map-0.0.1"
                            ];
                          })
                        ];
                      })
                      (sources."once-1.4.0" // {
                        dependencies = [
                          sources."wrappy-1.0.2"
                        ];
                      })
                      sources."path-is-absolute-1.0.1"
                    ];
                  })
                ];
              })
            ];
          })
          (sources."winston-2.1.1" // {
            dependencies = [
              sources."async-1.0.0"
              sources."colors-1.0.3"
              sources."cycle-1.0.3"
              sources."eyes-0.1.8"
              sources."isstream-0.1.2"
              sources."pkginfo-0.3.1"
              sources."stack-trace-0.0.9"
            ];
          })
        ];
      })
      (sources."request-2.75.0" // {
        dependencies = [
          sources."aws-sign2-0.6.0"
          sources."aws4-1.5.0"
          (sources."bl-1.1.2" // {
            dependencies = [
              (sources."readable-stream-2.0.6" // {
                dependencies = [
                  sources."core-util-is-1.0.2"
                  sources."inherits-2.0.3"
                  sources."isarray-1.0.0"
                  sources."process-nextick-args-1.0.7"
                  sources."string_decoder-0.10.31"
                  sources."util-deprecate-1.0.2"
                ];
              })
            ];
          })
          sources."caseless-0.11.0"
          (sources."combined-stream-1.0.5" // {
            dependencies = [
              sources."delayed-stream-1.0.0"
            ];
          })
          sources."extend-3.0.0"
          sources."forever-agent-0.6.1"
          (sources."form-data-2.0.0" // {
            dependencies = [
              sources."asynckit-0.4.0"
            ];
          })
          (sources."har-validator-2.0.6" // {
            dependencies = [
              (sources."chalk-1.1.3" // {
                dependencies = [
                  sources."ansi-styles-2.2.1"
                  sources."escape-string-regexp-1.0.5"
                  (sources."has-ansi-2.0.0" // {
                    dependencies = [
                      sources."ansi-regex-2.0.0"
                    ];
                  })
                  (sources."strip-ansi-3.0.1" // {
                    dependencies = [
                      sources."ansi-regex-2.0.0"
                    ];
                  })
                  sources."supports-color-2.0.0"
                ];
              })
              (sources."commander-2.9.0" // {
                dependencies = [
                  sources."graceful-readlink-1.0.1"
                ];
              })
              (sources."is-my-json-valid-2.15.0" // {
                dependencies = [
                  sources."generate-function-2.0.0"
                  (sources."generate-object-property-1.2.0" // {
                    dependencies = [
                      sources."is-property-1.0.2"
                    ];
                  })
                  sources."jsonpointer-4.0.0"
                  sources."xtend-4.0.1"
                ];
              })
              (sources."pinkie-promise-2.0.1" // {
                dependencies = [
                  sources."pinkie-2.0.4"
                ];
              })
            ];
          })
          (sources."hawk-3.1.3" // {
            dependencies = [
              sources."hoek-2.16.3"
              sources."boom-2.10.1"
              sources."cryptiles-2.0.5"
              sources."sntp-1.0.9"
            ];
          })
          (sources."http-signature-1.1.1" // {
            dependencies = [
              sources."assert-plus-0.2.0"
              (sources."jsprim-1.3.1" // {
                dependencies = [
                  sources."extsprintf-1.0.2"
                  sources."json-schema-0.2.3"
                  sources."verror-1.3.6"
                ];
              })
              (sources."sshpk-1.10.1" // {
                dependencies = [
                  sources."asn1-0.2.3"
                  sources."assert-plus-1.0.0"
                  sources."dashdash-1.14.0"
                  sources."getpass-0.1.6"
                  sources."jsbn-0.1.0"
                  sources."tweetnacl-0.14.3"
                  sources."jodid25519-1.0.2"
                  sources."ecc-jsbn-0.1.1"
                  sources."bcrypt-pbkdf-1.0.0"
                ];
              })
            ];
          })
          sources."is-typedarray-1.0.0"
          sources."isstream-0.1.2"
          sources."json-stringify-safe-5.0.1"
          (sources."mime-types-2.1.12" // {
            dependencies = [
              sources."mime-db-1.24.0"
            ];
          })
          sources."node-uuid-1.4.7"
          sources."oauth-sign-0.8.2"
          sources."qs-6.2.1"
          sources."stringstream-0.0.5"
          sources."tough-cookie-2.3.1"
          sources."tunnel-agent-0.4.3"
        ];
      })
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Tool for zipping and uploading a Plone theme over HTTP";
      license = "MIT";
    };
    production = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}
